{
 "title": "batch-processing-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "timeRate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "step seconds max",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spring_batch_step_seconds_max{application=\"batch-processing\"}",
     "legendFormat": "{{spring_batch_step_name}} max seconds"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"batch-processing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job launch total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spring_batch_job_launch_count_total{application=\"batch-processing\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}